### ISSUE TITLE
Configure the build options

### ISSUE THREAD

**Issue by joseluis** [fornwall/rust-script#116]
I'd love to be able to use rust-script to run no_std scripts that depend on custom build options, which normally are configured inside the `.cargo/config.toml` file. e.g.:
```toml
[build]
target = "x86_64-unknown-none"
rustflags = ["-C", "link-args=-N", "-C", "relocation-model=static"]
```

Ideally I'd love to be able to specify a section like this in the header:
```rs
//! ```config
//! [build]
//! target = "x86_64-unknown-none"
//! rustflags = ["-C", "link-args=-N", "-C", "relocation-model=static"]
//! ```
```
and it would be copied to the appropriate place like it happens now with the Cargo.toml.
